# Generated by Django 4.2.8 on 2023-12-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_sortendurl_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sortendurl",
            old_name="url",
            new_name="user_url",
        ),
        migrations.AddField(
            model_name="sortendurl",
            name="short url",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="sortendurl",
            name="visited url",
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
