# Generated by Django 4.2.8 on 2023-12-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_rename_url_sortendurl_user_url_sortendurl_short_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sortendurl",
            name="visited url",
            field=models.IntegerField(default=0),
        ),
    ]
